version: "3.9"

services:
  front:
    build:
      context: ./client/volt-client
      dockerfile: Dockerfile
      target: dev
    env_file: .env.dev
    ports:
      - "3000:3000"
  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: .env.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server/data:/app/data