version: "3.9"

services:
  front:
    image: ghcr.io/ouiouibaguette-2024/volt-client:main
    ports:
      - "3000:3000"
  back:
    image: ghcr.io/ouiouibaguette-2024/volt-server:main
    ports:
      - "8000:8000"
    volumes:
      - ./server/data:/app/data