name: Deploy stack to Self-hosted Portainer

on:
  push:
    tags:
      - '*-DEPLOY'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy stack

    steps:
      - uses: actions/checkout@v2
      - name: Deploy stack to Portainer
        uses: nvti/portainer-stack-deploy@v1.4
        with:
          portainerHost: datntdev0/action-deploy-to-portainer@v0.1.0
          portainerEnvId: 2
          portainerApiKey: ${{ secrets.PORTAINER_PAT }}
          portainerStackName: volt
          portainerFilePath: ./prod-docker-compose.yml