name: Build and push Docker images to GHCR

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.4.1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (client)
        uses: docker/build-push-action@v5
        with:
          target: prod
          context: ./client/volt-client
          file: ./client/volt-client/Dockerfile
          push: true
          tags: ghcr.io/ouiouibaguette-2024/volt-client:${{ env.GITHUB_REF_SLUG }}
      - name: Build and push (server)
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: ghcr.io/ouiouibaguette-2024/volt-server:${{ env.GITHUB_REF_SLUG }}